language: node_js
node_js:
  - "10"
install:
  - npm install
before_script:
  - npm run coveralls
script:
  - npm run build
deploy:
  provider: s3
  access_key_id:
    secure: o5CwaB/3H1IOU5XF+5Eq8jD/xxnkQLUreFj2z6wZ0M3gR/T+PypAslC6oTTt5yu1BVjv3z9z9ri7dPHasjfPixRFYwhRugJG/7Lv8ZiOVsFLJI+b1+HaqK1f6sy7GIQQ1F9nKX98FCS7gxCDQaBx1ovl2ARuaIP7UhTAkRpz2QuMB+xhOcEZjq0d27fTh8GEiD7Swd4IBPYHxwaQ+R8NuXOsmQeYfCoEew00MftYdPTiNqOrxo0utiznE0MOvsGoPi3O0tC8ZN0uFFhIx77ttmTnXNVm+hGeXU3AgoSVgEuF38cZ27Vk/12va4sR+mWD+ftjJasO2BADwd9uWQ/TTdD9enTFJY+90RYbsYvOpskt35IN0AMjUwjcbZ+VJm3AKxW9Z/3e92gz4kUc8Bi9nY5ZmqWrL/qA1PCFbikCWi0sv1OsIWUTNQni+E4w97TIHIhJdj7++qI94puWbVkpVCFFd5/myBnHK6ge2tiRqzIEAcurbwhZQxzPwwC1bjY2FpIVSYZQMFFY/u4y5fwkorJCBjOfJZJcy3ELF5y27QNHuRkNdZCYLody8TrUxVVCxExw5NJHzzGriduQknNxvmF96ineL1UAOINy/ySuzm3RIeVsAnOuG+pBsfxgF/cNUnt92ElCr6tBD9BtyciruRaFwXGq8gyk1BdnFLN6cyw=
  secret_access_key:
    secure: eYMTHZSPB/5NeckEHMZCiDEDSBzpezO8Ai/EoYKU1DDG53/R3waucP7FMqGNxpeCYRS3fpEy88nVOH+MSZxsvK76Qm51URwRxxUDcRtMcyCGyxts5lO7kxBwomc+JATrsXhY0hbdjge/9iaaHlfgATMe6e28iVAp13FeJk6KSKqmzUbxlCPv0nHarZJ01U1Icbj4PGTkB/7W1K5k0fk/vILLrVINsk7acLkP2XP8ClrR3rqFoxRIyjHKTYRTyyGS3JanlFhtKaWhP9mbQYdSyd3qgNlDexC+FsHzYcYEhy7UJ1jAya8rHF1zI6nHshaQPzDwbGVlCOJy9L0NMgPn37BmIXMv620ar77pT/7XSh6SRcs8/iXPH/A2e8mLBZizlJKjvlH5HEwzCydPB0qBfn4LJtUBtqtKuZ7XHkxi5mUe1LAICMi5mf7YJUL/e7VLrC1Z1Y6ok7dsXz152SCEyJAhOVuUvM74qb6JawFDTU4OWj/AcGCxtBrpmmWkEXUSDlND7bpO0fhvRLXO+jW2RCHjNdlgHJ6DF37hIR2jykjBJgA9TSfTema2OX0gYHK2yBuaQUHdeH/yKTZZJsARaj38fBY17OdVvuR1ESLS6WizKm5c75lFC4zzYXcLQsd3E8QOq/dVnAk9UvNDbSVVy95bAdYj1/4qhk9YJbstGLM=
  bucket: www.potsides.com
  region: eu-west-2
  skip_cleanup: true
  local_dir: build
  acl: public_read
